services:
  redis:
    image: redis:7-alpine
    container_name: mess-finder-redis
    ports:
      - "6379:6379"
    command: ["redis-server","--appendoly","yes"]
    volumes:
      - redis_data/data

  
  mongo:
    image: mongo:7
    container_name: mess-finder-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017" 
